-- H552_RND.V_AI_PHM_ADDR source
-- Employee Address View (사원 주소 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "V_AI_PHM_ADDR" (
    "EMP_ID",           -- 사원번호
    "EMP_NAME",         -- 이름
    "ADDRESS",          -- 주소
    "ADDRESS_DETAIL",   -- 상세주소
    "ZIP_CODE",         -- 우편번호
    "MODIFIED_DATE",    -- 수정일시
    "MODIFIED_BY"       -- 수정자
) AS
  SELECT
    PA.EMP_ID AS EMP_ID,
    PN_EMP.LAST_NM AS EMP_NAME,
    PA.ADDR AS ADDRESS,
    PA.DETAIL_ADDR AS ADDRESS_DETAIL,
    PA.ZIP_NO AS ZIP_CODE,
    PA.MOD_DATE AS MODIFIED_DATE,
    PN_MOD.LAST_NM AS MODIFIED_BY
FROM PHM_ADDR PA
JOIN PHM_NAME PN_EMP
  ON PA.EMP_ID = PN_EMP.EMP_ID
LEFT JOIN PHM_NAME PN_MOD
  ON PA.MOD_USER_ID = PN_MOD.EMP_ID;






-- H552_RND.V_AI_PHM_ARMY source
-- Military Service View (병역 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PHM_ARMY" (
    "EMP_ID",               -- 사원번호
    "EMP_NAME",             -- 이름
    "POSITION",             -- 직위
    "MILITARY_BRANCH",      -- 병과코드
    "MILITARY_RANK",        -- 계급
    "DISCHARGE_TYPE",       -- 전역구분
    "SPECIALTY",            -- 주특기
    "MILITARY_NUMBER",      -- 군번
    "EXEMPTION_REASON",     -- 미필사유
    "SERVICE_STATUS",       -- 군필구분
    "SERVICE_TYPE",         -- 복무형태
    "MILITARY_TYPE",        -- 군별구분
    "DISCHARGE_DATE"        -- 전역일자
) AS
  SELECT
    PA.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC.CD_NM AS POSITION,
    FC1.CD_NM AS MILITARY_BRANCH,
    FC2.CD_NM AS MILITARY_RANK,
    FC3.CD_NM AS DISCHARGE_TYPE,
    FC4.CD_NM AS SPECIALTY,
    PA.ARMY_NO AS MILITARY_NUMBER,
    PA.ARMY_NO_CD AS EXEMPTION_REASON,
    FC5.CD_NM AS SERVICE_STATUS,
    FC6.CD_NM AS SERVICE_TYPE,
    FC7.CD_NM AS MILITARY_TYPE,
    PA.OUT_YMD AS DISCHARGE_DATE
FROM PHM_ARMY PA
JOIN PHM_EMP PE
  ON PE.EMP_ID = PA.EMP_ID
JOIN PHM_NAME PN
  ON PN.EMP_ID = PA.EMP_ID
LEFT JOIN FRM_CODE FC
  ON FC.CD = PE.POS_CD
 AND FC.CD_KIND = 'PHM_POS_CD'
LEFT JOIN FRM_CODE FC1
  ON FC1.CD = PA.ARMY_BRANCH_CD
 AND FC1.CD_KIND = 'PHM_ARMY_BRANCH_CD'
LEFT JOIN FRM_CODE FC2
  ON FC2.CD = PA.ARMY_CLASS_CD
 AND FC2.CD_KIND = 'PHM_ARMY_CLASS_CD'
LEFT JOIN FRM_CODE FC3
  ON FC3.CD = PA.ARMY_DISCHARGE_CD
 AND FC3.CD_KIND = 'PHM_ARMY_DISCHARGE_CD'
LEFT JOIN FRM_CODE FC4
  ON FC4.CD = PA.ARMY_MTALENT_CD
 AND FC4.CD_KIND = 'PHM_ARMY_MTALENT_CD'
LEFT JOIN FRM_CODE FC5
  ON FC5.CD = PA.ARMY_NO_REASON_CD
 AND FC5.CD_KIND = 'PHM_ARMY_NO_REASON_CD'
LEFT JOIN FRM_CODE FC6
  ON FC6.CD = PA.ARMY_SERV_CD
 AND FC6.CD_KIND = 'PHMARMY_SERV_CD'
LEFT JOIN FRM_CODE FC7
  ON FC7.CD = PA.ARMY_TYPE_CD
 AND FC7.CD_KIND = 'PHM_ARMY_TYPE_CD';



-- H552_RND.V_AI_PHM_CAREER source
-- Career History View (경력 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PHM_CAREER" (
    "EMP_ID",               -- 사번
    "EMP_NAME",             -- 이름
    "POSITION",             -- 직위
    "COMPANY_NAME",         -- 근무기관
    "LOCATION",             -- 소재지
    "PREVIOUS_POSITION",    -- 전직장직위
    "ACTUAL_EXPERIENCE",    -- 실근무경력 (개월)
    "RECOGNITION_RATE",     -- 경력인정률
    "RESIGNATION_REASON"    -- 퇴사사유
) AS
  SELECT
    PC.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC2.CD_NM AS POSITION,
    PC.ORG_CORP_NM AS COMPANY_NAME,
    PC.PLACE_NM AS LOCATION,
    PC.POSITION_NM AS PREVIOUS_POSITION,
    PC.RCAREER_NUM AS ACTUAL_EXPERIENCE,
    PC.RECO_RATE AS RECOGNITION_RATE,
    PC.RETIRE_CAUSE AS RESIGNATION_REASON
FROM PHM_CAREER PC
JOIN PHM_EMP PE
  ON PE.EMP_ID = PC.EMP_ID
JOIN PHM_NAME PN
  ON PN.EMP_ID = PC.EMP_ID
LEFT JOIN FRM_CODE FC2
  ON FC2.CD = PE.POS_CD
 AND FC2.CD_KIND = 'PHM_POS_CD';


-- H552_RND.V_AI_PHM_EDU source
-- Education/Training View (교육 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PHM_EDU" (
    "EMP_ID",               -- 사원번호
    "EMP_NAME",             -- 이름
    "POSITION",             -- 직위
    "COURSE_TYPE",          -- 교육과정
    "COURSE_GRADE",         -- 교육등급
    "COURSE_FIELD",         -- 교육분야
    "COURSE_NAME",          -- 교육과정명
    "INSTITUTION_TYPE",     -- 교육기관
    "INSTITUTION_NAME",     -- 교육기관명
    "TRAINING_LOCATION",    -- 교육장소
    "TRAINING_TYPE",        -- 교육유형
    "TRAINING_YEAR",        -- 교육년도
    "START_DATE",           -- 시작일
    "END_DATE",             -- 종료일
    "TRAINING_COST",        -- 교육비
    "COMPLETION_POINTS",    -- 이수포인트
    "COMPLETION_HOURS",     -- 이수시간
    "COMPLETION_YN",        -- 수료여부
    "REFUND_AMOUNT"         -- 환급금
) AS
  SELECT
    PED.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC.CD_NM AS POSITION,
    FC1.CD_NM AS COURSE_TYPE,
    FC2.CD_NM AS COURSE_GRADE,
    FC3.CD_NM AS COURSE_FIELD,
    PED.EDU_NM AS COURSE_NAME,
    FC4.CD_NM AS INSTITUTION_TYPE,
    PED.EDU_ORG_NM AS INSTITUTION_NAME,
    FC5.CD_NM AS TRAINING_LOCATION,
    FC6.CD_NM AS TRAINING_TYPE,
    PED.EDU_YY AS TRAINING_YEAR,
    PED.STA_YMD AS START_DATE,
    PED.END_YMD AS END_DATE,
    PED.REAL_AMT AS TRAINING_COST,
    PED.RESULT_PNT AS COMPLETION_POINTS,
    PED.RESULT_TIMES AS COMPLETION_HOURS,
    PED.RESULT_YN AS COMPLETION_YN,
    PED.RETURN_AMT AS REFUND_AMOUNT
FROM PHM_EDU PED
JOIN PHM_EMP PE
  ON PE.EMP_ID = PED.EMP_ID
JOIN PHM_NAME PN
  ON PN.EMP_ID = PED.EMP_ID
LEFT JOIN FRM_CODE FC
  ON FC.CD = PE.POS_CD
 AND FC.CD_KIND = 'PHM_POS_CD'
LEFT JOIN FRM_CODE FC1
  ON FC1.CD = PED.EDU_CD
 AND FC1.CD_KIND = 'PHM_EDU_CD'
LEFT JOIN FRM_CODE FC2
  ON FC2.CD = PED.EDU_GRD_CD
 AND FC2.CD_KIND = 'PHM_EDU_GRD_CD'
LEFT JOIN FRM_CODE FC3
  ON FC3.CD = PED.EDU_KIND_CD
 AND FC3.CD_KIND = 'PHM_EDU_KIND_CD'
LEFT JOIN FRM_CODE FC4
  ON FC4.CD = PED.EDU_ORG_CD
 AND FC4.CD_KIND = 'PHM_EDU_ORG_CD'
LEFT JOIN FRM_CODE FC5
  ON FC5.CD = PED.EDU_PLA_CD
 AND FC5.CD_KIND = 'PHM_EDU_PLA_CD'
LEFT JOIN FRM_CODE FC6
  ON FC6.CD = PED.EDU_TYPE_CD
 AND FC6.CD_KIND = 'PHM_EDU_TYPE_CD';



-- H552_RND.V_AI_PHM_EMP source
-- Employee Master View (사원 기본 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PHM_EMP" (
    "EMP_ID",               -- 사원번호
    "EMP_NAME",             -- 이름
    "POSITION",             -- 직위
    "BIRTH_DATE",           -- 생년월일
    "CAREER_MONTHS",        -- 경력개월
    "JOB_TITLE",            -- 직책
    "JOB_TITLE_DATE",       -- 직책발령일자
    "EMPLOYEE_TYPE",        -- 직원구분
    "GENDER",               -- 성별
    "GROUP_JOIN_DATE",      -- 그룹입사일
    "HIRE_TYPE",            -- 입사구분
    "HIRE_DATE",            -- 입사일
    "ACTIVE_YN",            -- 재직여부
    "JOB_GRADE",            -- 직급
    "GRADE_PROMOTION_DATE", -- 직급발령일
    "RESIGNATION_TYPE",     -- 퇴사구분
    "RESIGNATION_DATE",     -- 퇴사일
    "PAY_STEP",             -- 호봉
    "PAY_STEP_DATE"         -- 호봉승급일
) AS
  SELECT
    PE.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC.CD_NM AS POSITION,
    PE.BIRTH_YMD AS BIRTH_DATE,
    PE.CAREER_NUM AS CAREER_MONTHS,
    FC3.CD_NM AS JOB_TITLE,
    PE.DUTY_YMD AS JOB_TITLE_DATE,
    FC4.CD_NM AS EMPLOYEE_TYPE,
    FC5.CD_NM AS GENDER,
    PE.GROUP_YMD AS GROUP_JOIN_DATE,
    FC6.CD_NM AS HIRE_TYPE,
    PE.HIRE_YMD AS HIRE_DATE,
    PE.IN_OFFI_YN AS ACTIVE_YN,
    FC8.CD_NM AS JOB_GRADE,
    PE.POS_GRD_YMD AS GRADE_PROMOTION_DATE,
    FC9.CD_NM AS RESIGNATION_TYPE,
    PE.RETIRE_YMD AS RESIGNATION_DATE,
    FC10.CD_NM AS PAY_STEP,
    PE.YEARNUM_YMD AS PAY_STEP_DATE
FROM PHM_EMP PE
JOIN PHM_NAME PN
  ON PN.EMP_ID = PE.EMP_ID
LEFT JOIN FRM_CODE FC
  ON FC.CD = PE.POS_CD
 AND FC.CD_KIND = 'PHM_POS_CD'
LEFT JOIN FRM_CODE FC3
  ON FC3.CD = PE.DUTY_CD
 AND FC3.CD_KIND = 'PHM_DUTY_CD'
LEFT JOIN FRM_CODE FC4
  ON FC4.CD = PE.EMP_KIND_CD
 AND FC4.CD_KIND = 'PHM_EMP_KIND_CD'
LEFT JOIN FRM_CODE FC5
  ON FC5.CD = PE.GENDER_CD
 AND FC5.CD_KIND = 'PHM_GENDER_CD'
LEFT JOIN FRM_CODE FC6
  ON FC6.CD = PE.HIRE_CD
 AND FC6.CD_KIND = 'CAM_CAU_CD'
LEFT JOIN FRM_CODE FC8
  ON FC8.CD = PE.POS_GRD_CD
 AND FC8.CD_KIND = 'PHM_POS_GRD_CD'
LEFT JOIN FRM_CODE FC9
  ON FC9.CD = PE.RETIRE_TYPE_CD
 AND FC9.CD_KIND = 'CAM_CAU_CD'
LEFT JOIN FRM_CODE FC10
  ON FC10.CD = PE.YEARNUM_CD
 AND FC10.CD_KIND = 'PHM_HOBONG';


-- H552_RND.V_AI_PHM_FAMILY source
-- Family Member View (가족 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PHM_FAMILY" (
    "EMP_ID",               -- 사원번호
    "EMP_NAME",             -- 사원 이름
    "FAMILY_BIRTH_DATE",    -- 가족 생년월일
    "FAMILY_COMPANY",       -- 가족 직장명
    "FAMILY_LAST_NAME",     -- 가족 성
    "RELATIONSHIP",         -- 관계
    "FAMILY_GENDER_CODE",   -- 가족 성별코드
    "FAMILY_GENDER",        -- 가족 성별
    "DISABILITY_CODE",      -- 장애코드
    "DISABILITY_NAME",      -- 장애명
    "DISABILITY_YN",        -- 장애여부
    "FAMILY_POSITION",      -- 가족 직위
    "FAMILY_SCHOOL"         -- 가족 출신학교
) AS
  SELECT
    PF.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    PF.BIRTH_YMD AS FAMILY_BIRTH_DATE,
    PF.COMPANY_NM AS FAMILY_COMPANY,
    PF.FAM_FIRST_NM AS FAMILY_LAST_NAME,
    FC_REL.CD_NM AS RELATIONSHIP,
    PF.GENDER_CD AS FAMILY_GENDER_CODE,
    FC_GEN.CD_NM AS FAMILY_GENDER,
    PF.HANDICAP_GRD_CD AS DISABILITY_CODE,
    FC_HAN.CD_NM AS DISABILITY_NAME,
    PF.HANICAP_YN AS DISABILITY_YN,
    PF.POSITION_NM AS FAMILY_POSITION,
    PF.SCH_NM AS FAMILY_SCHOOL
FROM PHM_FAMILY PF
JOIN PHM_NAME PN
  ON PF.EMP_ID = PN.EMP_ID
LEFT JOIN FRM_CODE FC_REL
  ON PF.FAM_REL_CD = FC_REL.CD
 AND FC_REL.CD_KIND = 'PHM_FAM_REL_CD'
LEFT JOIN FRM_CODE FC_GEN
  ON PF.GENDER_CD = FC_GEN.CD
 AND FC_GEN.CD_KIND = 'PHM_GENDER_CD'
LEFT JOIN FRM_CODE FC_HAN
  ON PF.HANDICAP_GRD_CD = FC_HAN.CD
 AND FC_HAN.CD_KIND = 'PHM_HANDICAP_GRD_CD';



-- H552_RND.V_AI_PHM_LANG_EST source
-- Language Assessment View (어학 평가 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PHM_LANG_EST" (
    "EMP_ID",               -- 사원번호
    "EMP_NAME",             -- 이름
    "POSITION",             -- 직위
    "LANGUAGE_TYPE",        -- 어학구분 (영어, 일어 등)
    "LANGUAGE_LEVEL",       -- 어학등급
    "ASSESSMENT_ORG_TYPE",  -- 평가기관 (TOEIC, JLPT 등)
    "ASSESSMENT_ORG_NAME",  -- 평가기관명
    "SCORE",                -- 어학점수
    "ACQUIRED_DATE",        -- 취득일자
    "SEQUENCE",             -- 차수
    "ASSESSMENT_YEAR"       -- 년도
) AS
  SELECT
    PL.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC.CD_NM AS POSITION,
    FC1.CD_NM AS LANGUAGE_TYPE,
    FC2.CD_NM AS LANGUAGE_LEVEL,
    FC3.CD_NM AS ASSESSMENT_ORG_TYPE,
    PL.EST_ORG_NM AS ASSESSMENT_ORG_NAME,
    PL.EST_PNT AS SCORE,
    PL.EST_YMD AS ACQUIRED_DATE,
    PL.STD_SEQ AS SEQUENCE,
    PL.STD_YY AS ASSESSMENT_YEAR
FROM PHM_LANG_EST PL
JOIN PHM_EMP PE
  ON PE.EMP_ID = PL.EMP_ID
JOIN PHM_NAME PN
  ON PN.EMP_ID = PL.EMP_ID
LEFT JOIN FRM_CODE FC
  ON FC.CD = PE.POS_CD
 AND FC.CD_KIND = 'PHM_POS_CD'
LEFT JOIN FRM_CODE FC1
  ON FC1.CD = PL.EST_CD
 AND FC1.CD_KIND = 'PHM_EST_CD'
LEFT JOIN FRM_CODE FC2
  ON FC2.CD = PL.EST_GRD_CD
 AND FC2.CD_KIND = 'PHM_EST_GRD_CD'
LEFT JOIN FRM_CODE FC3
  ON FC3.CD = PL.EST_ORG_CD
 AND FC3.CD_KIND = 'PHM_EST_ORG_CD';


-- H552_RND.V_AI_PHM_LICENSE source
-- License/Certification View (자격증 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PHM_LICENSE" (
    "EMP_ID",               -- 사원번호
    "EMP_NAME",             -- 이름
    "POSITION",             -- 직위
    "ALLOWANCE_TYPE",       -- 수당지급구분
    "CERTIFICATE_ID",       -- 증명서ID
    "EXPIRY_DATE",          -- 유효일자
    "LICENSE_NAME",         -- 자격증이름
    "LICENSE_NUMBER",       -- 자격증번호
    "LICENSE_TYPE",         -- 자격구분
    "ISSUING_ORG",          -- 발급기관
    "ISSUE_DATE"            -- 발급일
) AS
  SELECT
    PL.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC.CD_NM AS POSITION,
    PL.BONUS_TYPE AS ALLOWANCE_TYPE,
    PL.CTF_FILE_ID AS CERTIFICATE_ID,
    PL.END_YMD AS EXPIRY_DATE,
    FC1.CD_NM AS LICENSE_NAME,
    PL.LICENSE_NO AS LICENSE_NUMBER,
    FC2.CD_NM AS LICENSE_TYPE,
    PL.ORG_NM AS ISSUING_ORG,
    PL.STA_YMD AS ISSUE_DATE
FROM PHM_LICENSE PL
JOIN PHM_EMP PE
  ON PE.EMP_ID = PL.EMP_ID
JOIN PHM_NAME PN
  ON PN.EMP_ID = PL.EMP_ID
LEFT JOIN FRM_CODE FC
  ON FC.CD = PE.POS_CD
 AND FC.CD_KIND = 'PHM_POS_CD'
LEFT JOIN FRM_CODE FC1
  ON FC1.CD = PL.LICENSE_CD
 AND FC1.CD_KIND = 'PHM_LICENSE_CD'
LEFT JOIN FRM_CODE FC2
  ON FC2.CD = PL.LICENSE_TYPE_CD
 AND FC2.CD_KIND = 'PHM_LICENSE_TYPE_CD';


-- H552_RND.V_AI_PHM_SCHOLAR source
-- Education Background View (학력 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PHM_SCHOLAR" (
    "EMP_ID",               -- 사원번호
    "EMP_NAME",             -- 이름
    "POSITION",             -- 직위
    "MAJOR_CODE",           -- 졸업학과 코드
    "MAJOR_NAME",           -- 졸업학과명
    "DOUBLE_MAJOR_NAME",    -- 복수전공명
    "SCHOOL_NAME",          -- 학교명
    "ADMISSION_DATE",       -- 입학일
    "GRADUATION_DATE",      -- 졸업일
    "MINOR_CODE",           -- 부전공코드
    "MINOR_NAME",           -- 부전공명
    "SCHOOL_LOCATION_CODE", -- 학교소재지 코드
    "SCHOOL_LOCATION_NAME"  -- 학교소재지명
) AS
  SELECT
    PS.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC.CD_NM AS POSITION,
    PS.MAJOR_CD AS MAJOR_CODE,
    PS.MAJOR_NM AS MAJOR_NAME,
    PS.DOU_MAJOR_NM AS DOUBLE_MAJOR_NAME,
    FC2.CD_NM AS SCHOOL_NAME,
    PS.STA_YM AS ADMISSION_DATE,
    PS.END_YM AS GRADUATION_DATE,
    PS.SUB_MAJOR_CD AS MINOR_CODE,
    PS.SUB_MAJOR_NM AS MINOR_NAME,
    PS.SCH_PLACE_CD AS SCHOOL_LOCATION_CODE,
    PS.SCH_PLACE_NM AS SCHOOL_LOCATION_NAME
FROM PHM_SCHOLAR PS
JOIN PHM_EMP PE
  ON PE.EMP_ID = PS.EMP_ID
JOIN PHM_NAME PN
  ON PN.EMP_ID = PS.EMP_ID
LEFT JOIN FRM_CODE FC2
  ON FC2.CD = PS.SCH_CD
 AND FC2.CD_KIND = 'PHM_SCH_CD'
LEFT JOIN FRM_CODE FC
  ON FC.CD = PE.POS_CD
 AND FC.CD_KIND = 'PHM_POS_CD';


-- H552_RND.V_AI_PPM_MNT source
-- Rewards & Penalties View (상벌 정보)

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_PPM_MNT" (
    "EMP_ID",               -- 사원번호
    "EMP_NAME",             -- 이름
    "POSITION",             -- 직위
    "ACTIVE_STATUS",        -- 재직여부
    "REWARD_CATEGORY",      -- 상벌종류
    "REASON",               -- 상벌사유
    "RECORD_ID",            -- 상벌ID
    "REWARD_AMOUNT",        -- 포상금액
    "RECORD_NUMBER",        -- 상벌번호
    "AWARDING_ORG",         -- 포상기관
    "AWARD_DATE",           -- 포상일자
    "DESCRIPTION",          -- 상벌내용
    "REWARD_TYPE"           -- 상벌구분 (상/벌)
) AS
  SELECT
    PM.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC.CD_NM AS POSITION,
    FC1.CD_NM AS ACTIVE_STATUS,
    FC2.CD_NM AS REWARD_CATEGORY,
    PM.PPM_DESC AS REASON,
    PM.PPM_MNT_ID AS RECORD_ID,
    PM.PPM_MON AS REWARD_AMOUNT,
    PM.PPM_NO AS RECORD_NUMBER,
    PM.PPM_ORG_NM AS AWARDING_ORG,
    PM.PPM_YMD AS AWARD_DATE,
    PM.PRIZE_DESC AS DESCRIPTION,
    FC3.CD_NM AS REWARD_TYPE
FROM PPM_MNT PM
JOIN PHM_EMP PE
  ON PE.EMP_ID = PM.EMP_ID
JOIN PHM_NAME PN
  ON PN.EMP_ID = PM.EMP_ID
LEFT JOIN FRM_CODE FC
  ON FC.CD = PE.POS_CD
 AND FC.CD_KIND = 'PHM_POS_CD'
LEFT JOIN FRM_CODE FC1
  ON FC1.CD = PM.INOFF_CD
 AND FC1.CD_KIND = 'PPM_INOFF_CD'
LEFT JOIN FRM_CODE FC2
  ON FC2.CD = PM.KIND_CD
 AND FC2.CD_KIND = 'PPM_KIND_CD'
LEFT JOIN FRM_CODE FC3
  ON FC3.CD = PM.TYPE_CD
 AND FC3.CD_KIND = 'PPM_TYPE_CD';

