-- H552_RND.V_AI_EMPLOYEE source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_EMPLOYEE" ("EMP_ID", "EMP_NAME", "EMP_NAME_ENG", "POSITION", "BIRTH_DATE", "DEPARTMENT", "CAREER_MONTHS", "CAREER_YEARS", "DUTY", "DUTY_DATE", "EMP_TYPE", "GENDER", "GROUP_JOIN_DATE", "HIRE_TYPE", "HIRE_DATE", "WORK_STATUS", "GRADE", "GRADE_DATE", "RETIRE_REASON", "RETIRE_DATE", "SALARY_STEP", "SALARY_STEP_DATE") AS
  SELECT
    PE.EMP_ID                   AS EMP_ID,
    PN.KOR_NAME                 AS EMP_NAME,
    PN.ENG_NAME                 AS EMP_NAME_ENG,
    FC.CD_NM                    AS POSITION,
    PE.BIRTH_YMD                AS BIRTH_DATE,
    FC11.CD_NM                  AS DEPARTMENT,
    PE.CAREER_NUM               AS CAREER_MONTHS,
    TRUNC(PE.CAREER_NUM / 12)   AS CAREER_YEARS,
    FC3.CD_NM                   AS DUTY,
    PE.DUTY_YMD                 AS DUTY_DATE,
    FC4.CD_NM                   AS EMP_TYPE,
    FC5.CD_NM                   AS GENDER,
    PE.GROUP_YMD                AS GROUP_JOIN_DATE,
    FC6.CD_NM                   AS HIRE_TYPE,
    PE.HIRE_YMD                 AS HIRE_DATE,
    CASE PE.IN_OFFI_YN
        WHEN 'Y' THEN '재직'
        WHEN 'N' THEN '퇴직'
        ELSE PE.IN_OFFI_YN
    END                         AS WORK_STATUS,
    FC8.CD_NM                   AS GRADE,
    PE.POS_GRD_YMD              AS GRADE_DATE,
    FC9.CD_NM                   AS RETIRE_REASON,
    PE.RETIRE_YMD               AS RETIRE_DATE,
    FC10.CD_NM                  AS SALARY_STEP,
    PE.YEARNUM_YMD              AS SALARY_STEP_DATE
FROM PHM_EMP PE
LEFT JOIN (
    SELECT EMP_ID,
           MAX(CASE WHEN NAME_TYPE_CD = 'KOR' THEN LAST_NM END) AS KOR_NAME,
           MAX(CASE WHEN NAME_TYPE_CD = 'ENG' THEN LAST_NM END) AS ENG_NAME
    FROM PHM_NAME
    GROUP BY EMP_ID
) PN ON PN.EMP_ID = PE.EMP_ID
LEFT JOIN FRM_CODE FC ON FC.CD = PE.POS_CD AND FC.CD_KIND = 'PHM_POS_CD'
LEFT JOIN FRM_CODE FC3 ON FC3.CD = PE.DUTY_CD AND FC3.CD_KIND = 'PHM_DUTY_CD'
LEFT JOIN FRM_CODE FC4 ON FC4.CD = PE.EMP_KIND_CD AND FC4.CD_KIND = 'PHM_EMP_KIND_CD'
LEFT JOIN FRM_CODE FC5 ON FC5.CD = PE.GENDER_CD AND FC5.CD_KIND = 'PHM_GENDER_CD'
LEFT JOIN FRM_CODE FC6 ON FC6.CD = PE.HIRE_CD AND FC6.CD_KIND = 'CAM_CAU_CD'
LEFT JOIN FRM_CODE FC8 ON FC8.CD = PE.POS_GRD_CD AND FC8.CD_KIND = 'PHM_POS_GRD_CD'
LEFT JOIN FRM_CODE FC9 ON FC9.CD = PE.RETIRE_TYPE_CD AND FC9.CD_KIND = 'CAM_CAU_CD'
LEFT JOIN FRM_CODE FC11 ON FC11.CD = PE.ORG_ID AND FC11.CD_KIND = 'CPE_GROUP_CD'
LEFT JOIN FRM_CODE FC10 ON FC10.CD = PE.YEARNUM_CD AND FC10.CD_KIND = 'PHM_HOBONG';

GRANT SELECT ON "H552_RND"."V_AI_EMPLOYEE" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.EMP_ID IS '직원 고유 ID (다른 뷰와 조인 키)';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.EMP_NAME IS '직원 이름 (한글)';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.EMP_NAME_ENG IS '직원 영문 이름';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE."POSITION" IS '직위 (사원, 대리, 과장, 차장, 부장, 이사, 전무이사, 사장, 회장 등)';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.BIRTH_DATE IS '생년월일';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.DEPARTMENT IS '부서명';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.CAREER_MONTHS IS '총 경력 개월수';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.CAREER_YEARS IS '총 경력 연수';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.DUTY IS '현재 직무/담당업무';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.DUTY_DATE IS '직무 배치일';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.EMP_TYPE IS '고용형태 (정규직, 계약직, 인턴 등)';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.GENDER IS '성별 (남, 여)';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.GROUP_JOIN_DATE IS '그룹 입사일 (그룹사 내 이동 시 최초 입사일)';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.HIRE_TYPE IS '채용유형 (신입, 경력, 입사(신입), 입사(경력) 등)';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.HIRE_DATE IS '입사일 ★ 입사자 수 집계 시 사용 (TO_CHAR(HIRE_DATE, ''YYYY'') = ''2024'')';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.WORK_STATUS IS '재직상태 (재직, 퇴직) ★ 현재 재직자/퇴직자 조회 시 사용';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.GRADE IS '직급/등급(★ 직위아님- 대리,과장,차장,부장등 아님)';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.GRADE_DATE IS '직급/등급 변경일';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.RETIRE_REASON IS '퇴직 사유';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.RETIRE_DATE IS '퇴직일 ★ 퇴사자 수 집계 시 사용 (TO_CHAR(RETIRE_DATE, ''YYYY'') = ''2024'')';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.SALARY_STEP IS '호봉/급여 단계';
COMMENT ON COLUMN H552_RND.V_AI_EMPLOYEE.SALARY_STEP_DATE IS '호봉/급여 단계 변경일';




-- H552_RND.V_AI_ADDRESS source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_ADDRESS" ("EMP_ID", "ADDRESS", "ADDRESS_DETAIL", "ZIP_CODE", "REGION", "MOD_DATE") AS
  SELECT
    PA.EMP_ID                   AS EMP_ID,
    PA.ADDR                     AS ADDRESS,
    PA.DETAIL_ADDR              AS ADDRESS_DETAIL,
    PA.ZIP_NO                   AS ZIP_CODE,
    CASE
        WHEN PA.ADDR LIKE '서울%' THEN '서울'
        WHEN PA.ADDR LIKE '부산%' THEN '부산'
        WHEN PA.ADDR LIKE '대구%' THEN '대구'
        WHEN PA.ADDR LIKE '인천%' THEN '인천'
        WHEN PA.ADDR LIKE '광주%' THEN '광주'
        WHEN PA.ADDR LIKE '대전%' THEN '대전'
        WHEN PA.ADDR LIKE '울산%' THEN '울산'
        WHEN PA.ADDR LIKE '세종%' THEN '세종'
        WHEN PA.ADDR LIKE '경기%' THEN '경기'
        WHEN PA.ADDR LIKE '강원%' THEN '강원'
        WHEN PA.ADDR LIKE '충북%' OR PA.ADDR LIKE '충청북%' THEN '충북'
        WHEN PA.ADDR LIKE '충남%' OR PA.ADDR LIKE '충청남%' THEN '충남'
        WHEN PA.ADDR LIKE '전북%' OR PA.ADDR LIKE '전라북%' THEN '전북'
        WHEN PA.ADDR LIKE '전남%' OR PA.ADDR LIKE '전라남%' THEN '전남'
        WHEN PA.ADDR LIKE '경북%' OR PA.ADDR LIKE '경상북%' THEN '경북'
        WHEN PA.ADDR LIKE '경남%' OR PA.ADDR LIKE '경상남%' THEN '경남'
        WHEN PA.ADDR LIKE '제주%' THEN '제주'
        ELSE '기타'
    END                         AS REGION,
    PA.MOD_DATE                 AS MOD_DATE
FROM PHM_ADDR PA;

GRANT SELECT ON "H552_RND"."V_AI_ADDRESS" TO "MUSER";

COMMENT ON TABLE H552_RND.V_AI_ADDRESS IS '사원 주소 정보 (EMP_ID로 V_AI_EMPLOYEE와 JOIN)';
COMMENT ON COLUMN H552_RND.V_AI_ADDRESS.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_ADDRESS.ADDRESS IS '기본 주소';
COMMENT ON COLUMN H552_RND.V_AI_ADDRESS.ADDRESS_DETAIL IS '상세 주소';
COMMENT ON COLUMN H552_RND.V_AI_ADDRESS.ZIP_CODE IS '우편번호';
COMMENT ON COLUMN H552_RND.V_AI_ADDRESS.REGION IS '거주 시/도 (서울, 경기 등)';
COMMENT ON COLUMN H552_RND.V_AI_ADDRESS.MOD_DATE IS '수정일시';


-- H552_RND.V_AI_CAREER source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_CAREER" ("EMP_ID", "PREV_COMPANY", "LOCATION", "PREV_POSITION", "WORK_MONTHS", "WORK_YEARS", "RECOGNITION_RATE", "LEAVE_REASON") AS
  SELECT
    PC.EMP_ID                   AS EMP_ID,
    PC.ORG_CORP_NM              AS PREV_COMPANY,
    PC.PLACE_NM                 AS LOCATION,
    PC.POSITION_NM              AS PREV_POSITION,
    PC.RCAREER_NUM              AS WORK_MONTHS,
    TRUNC(PC.RCAREER_NUM / 12)  AS WORK_YEARS,
    PC.RECO_RATE                AS RECOGNITION_RATE,
    PC.RETIRE_CAUSE             AS LEAVE_REASON
FROM PHM_CAREER PC;

GRANT SELECT ON "H552_RND"."V_AI_CAREER" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_CAREER.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_CAREER.PREV_COMPANY IS '이전에 근무한 회사명';
COMMENT ON COLUMN H552_RND.V_AI_CAREER.LOCATION IS '전직장 소재지';
COMMENT ON COLUMN H552_RND.V_AI_CAREER.PREV_POSITION IS '전직장 직위';
COMMENT ON COLUMN H552_RND.V_AI_CAREER.WORK_MONTHS IS '해당 직장 근무 개월 수';
COMMENT ON COLUMN H552_RND.V_AI_CAREER.WORK_YEARS IS '해당 직장 근무 연수';
COMMENT ON COLUMN H552_RND.V_AI_CAREER.RECOGNITION_RATE IS '경력 인정 비율 (%)';


-- H552_RND.V_AI_EDUCATION source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_EDUCATION" ("EMP_ID", "SCHOOL_NAME", "SCHOOL_LOCATION", "MAJOR", "DOUBLE_MAJOR", "MINOR", "ADMISSION_DATE", "GRADUATION_DATE", "GRADUATION_YEAR") AS
  SELECT
    PS.EMP_ID                   AS EMP_ID,
    FC2.CD_NM                   AS SCHOOL_NAME,
    PS.SCH_PLACE_NM             AS SCHOOL_LOCATION,
    PS.MAJOR_NM                 AS MAJOR,
    PS.DOU_MAJOR_NM             AS DOUBLE_MAJOR,
    PS.SUB_MAJOR_NM             AS MINOR,
    PS.STA_YM                   AS ADMISSION_DATE,
    PS.END_YM                   AS GRADUATION_DATE,
    CASE
        WHEN PS.END_YM IS NOT NULL THEN
            SUBSTR(PS.END_YM, 1, 4)
        ELSE NULL
    END                         AS GRADUATION_YEAR
FROM PHM_SCHOLAR PS
LEFT JOIN FRM_CODE FC2 ON FC2.CD = PS.SCH_CD AND FC2.CD_KIND = 'PHM_SCH_CD';

GRANT SELECT ON "H552_RND"."V_AI_EDUCATION" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_EDUCATION.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_EDUCATION.SCHOOL_NAME IS '졸업 학교명';
COMMENT ON COLUMN H552_RND.V_AI_EDUCATION.SCHOOL_LOCATION IS '학교 소재지';
COMMENT ON COLUMN H552_RND.V_AI_EDUCATION.MAJOR IS '전공 학과명';
COMMENT ON COLUMN H552_RND.V_AI_EDUCATION.DOUBLE_MAJOR IS '복구전공 명';
COMMENT ON COLUMN H552_RND.V_AI_EDUCATION.GRADUATION_DATE IS '졸업일시';
COMMENT ON COLUMN H552_RND.V_AI_EDUCATION.GRADUATION_YEAR IS '졸업 연도 (YYYY)';


-- H552_RND.V_AI_FAMILY source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_FAMILY" ("EMP_ID", "RELATION", "FAMILY_NAME", "FAMILY_GENDER", "FAMILY_BIRTH_DATE", "FAMILY_COMPANY", "FAMILY_POSITION", "FAMILY_SCHOOL", "DISABILITY_STATUS", "DISABILITY_GRADE") AS
  SELECT
    PF.EMP_ID                   AS EMP_ID,
    FC_REL.CD_NM                AS RELATION,
    PF.FAM_FIRST_NM             AS FAMILY_NAME,
    FC_GEN.CD_NM                AS FAMILY_GENDER,
    PF.BIRTH_YMD                AS FAMILY_BIRTH_DATE,
    PF.COMPANY_NM               AS FAMILY_COMPANY,
    PF.POSITION_NM              AS FAMILY_POSITION,
    PF.SCH_NM                   AS FAMILY_SCHOOL,
    CASE PF.HANICAP_YN
        WHEN 'Y' THEN '장애있음'
        WHEN 'N' THEN '장애없음'
        ELSE PF.HANICAP_YN
    END                         AS DISABILITY_STATUS,
    FC_HAN.CD_NM                AS DISABILITY_GRADE
FROM PHM_FAMILY PF
LEFT JOIN FRM_CODE FC_REL ON PF.FAM_REL_CD = FC_REL.CD AND FC_REL.CD_KIND = 'PHM_FAM_REL_CD'
LEFT JOIN FRM_CODE FC_GEN ON PF.GENDER_CD = FC_GEN.CD AND FC_GEN.CD_KIND = 'PHM_GENDER_CD'
LEFT JOIN FRM_CODE FC_HAN ON PF.HANDICAP_GRD_CD = FC_HAN.CD AND FC_HAN.CD_KIND = 'PHM_HANDICAP_GRD_CD';

GRANT SELECT ON "H552_RND"."V_AI_FAMILY" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_FAMILY.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_FAMILY.RELATION IS '가족 관계 (배우자, 자녀, 부모 등)';
COMMENT ON COLUMN H552_RND.V_AI_FAMILY.FAMILY_NAME IS '가족 구성원 이름';
COMMENT ON COLUMN H552_RND.V_AI_FAMILY.FAMILY_GENDER IS '가족 성별';
COMMENT ON COLUMN H552_RND.V_AI_FAMILY.FAMILY_BIRTH_DATE IS '가족 생년월일';
COMMENT ON COLUMN H552_RND.V_AI_FAMILY.FAMILY_COMPANY IS '가족 근무회사';
COMMENT ON COLUMN H552_RND.V_AI_FAMILY.FAMILY_POSITION IS '가족 근무회사 직위';
COMMENT ON COLUMN H552_RND.V_AI_FAMILY.FAMILY_SCHOOL IS '가족 출신학교';
COMMENT ON COLUMN H552_RND.V_AI_FAMILY.DISABILITY_STATUS IS '장애 여부 (장애있음, 장애없음)';


-- H552_RND.V_AI_LANGUAGE source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_LANGUAGE" ("EMP_ID", "LANGUAGE_TYPE", "EXAM_TYPE", "EXAM_INSTITUTION", "SCORE", "LANGUAGE_GRADE", "EXAM_DATE", "EXAM_YEAR", "EVALUATION_YEAR", "EVALUATION_SEQ") AS
  SELECT
    PL.EMP_ID                   AS EMP_ID,
    FC1.CD_NM                   AS LANGUAGE_TYPE,
    FC2.CD_NM                   AS EXAM_TYPE,
    FC4.CD_NM               AS EXAM_INSTITUTION,
    PL.EST_PNT                  AS SCORE,
    PL.EST_GRD_CD                   AS LANGUAGE_GRADE,
    PL.EST_YMD                  AS EXAM_DATE,
    CASE
        WHEN PL.EST_YMD IS NOT NULL THEN
            SUBSTR(PL.EST_YMD, 1, 4)
        ELSE NULL
    END                         AS EXAM_YEAR,
    PL.STD_YY                   AS EVALUATION_YEAR,
    PL.STD_SEQ                  AS EVALUATION_SEQ
FROM PHM_LANG_EST PL
LEFT JOIN FRM_CODE FC1 ON FC1.CD = PL.LANG_CD AND FC1.CD_KIND = 'PHM_LANG_CD'
LEFT JOIN FRM_CODE FC2 ON FC2.CD = PL.EST_CD AND FC2.CD_KIND = 'PHM_EST_CD'
LEFT JOIN FRM_CODE FC3 ON FC3.CD = PL.EST_ORG_CD AND FC3.CD_KIND = 'REM_LANG_LEVEL_CD'
LEFT JOIN FRM_CODE FC4 ON FC4.CD = PL.EST_ORG_CD AND FC4.CD_KIND = 'PHM_EST_ORG_CD'
;

GRANT SELECT ON "H552_RND"."V_AI_LANGUAGE" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_LANGUAGE.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_LANGUAGE.LANGUAGE_TYPE IS '어학 종류 (영어, 일본어, 중국어 등)';
COMMENT ON COLUMN H552_RND.V_AI_LANGUAGE.EXAM_TYPE IS '시험 종류 (TOEIC, TOEFL, JLPT 등)';
COMMENT ON COLUMN H552_RND.V_AI_LANGUAGE.SCORE IS '어학 시험 점수';
COMMENT ON COLUMN H552_RND.V_AI_LANGUAGE.LANGUAGE_GRADE IS '어학 등급';
COMMENT ON COLUMN H552_RND.V_AI_LANGUAGE.EXAM_YEAR IS '시험 응시 연도 (YYYY)';

-- H552_RND.V_AI_LICENSE source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_LICENSE" ("EMP_ID", "LICENSE_TYPE", "LICENSE_NAME", "LICENSE_NO", "ISSUING_ORG", "ISSUE_DATE", "EXPIRY_DATE", "VALIDITY_STATUS", "ALLOWANCE_TYPE") AS
  SELECT
    PL.EMP_ID                   AS EMP_ID,
    FC2.CD_NM                   AS LICENSE_TYPE,
    FC1.CD_NM                   AS LICENSE_NAME,
    PL.LICENSE_NO               AS LICENSE_NO,
    PL.ORG_NM                   AS ISSUING_ORG,
    PL.STA_YMD                  AS ISSUE_DATE,
    PL.END_YMD                  AS EXPIRY_DATE,
    CASE
        WHEN PL.END_YMD IS NOT NULL AND REGEXP_LIKE(PL.END_YMD, '^\d{8}$') AND PL.END_YMD < TO_CHAR(SYSDATE, 'YYYYMMDD') THEN '만료'
        WHEN PL.END_YMD IS NOT NULL AND REGEXP_LIKE(PL.END_YMD, '^\d{8}$') AND PL.END_YMD >= TO_CHAR(SYSDATE, 'YYYYMMDD') THEN '유효'
        WHEN PL.END_YMD IS NULL OR NOT REGEXP_LIKE(NVL(PL.END_YMD, ''), '^\d{8}$') THEN '영구'
        ELSE '확인필요'
    END                         AS VALIDITY_STATUS,
    PL.BONUS_TYPE               AS ALLOWANCE_TYPE
FROM PHM_LICENSE PL
LEFT JOIN FRM_CODE FC1 ON FC1.CD = PL.LICENSE_CD AND FC1.CD_KIND = 'PHM_LICENSE_CD'
LEFT JOIN FRM_CODE FC2 ON FC2.CD = PL.LICENSE_TYPE_CD AND FC2.CD_KIND = 'PHM_LICENSE_TYPE_CD';

GRANT SELECT ON "H552_RND"."V_AI_LICENSE" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_LICENSE.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_LICENSE.LICENSE_TYPE IS '자격 구분 (국가자격, 민간자격 등)';
COMMENT ON COLUMN H552_RND.V_AI_LICENSE.LICENSE_NAME IS '자격증 이름';
COMMENT ON COLUMN H552_RND.V_AI_LICENSE.LICENSE_NO IS '자격증 번호';
COMMENT ON COLUMN H552_RND.V_AI_LICENSE.ISSUING_ORG IS '발급기관';
COMMENT ON COLUMN H552_RND.V_AI_LICENSE.ISSUE_DATE IS '자격증 취득일';
COMMENT ON COLUMN H552_RND.V_AI_LICENSE.EXPIRY_DATE IS '자격증 만료일';
COMMENT ON COLUMN H552_RND.V_AI_LICENSE.VALIDITY_STATUS IS '자격증 유효 상태 (유효, 만료, 영구)';


-- H552_RND.V_AI_MILITARY source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_MILITARY" ("EMP_ID", "MILITARY_TYPE", "MILITARY_BRANCH", "MILITARY_RANK", "SERVICE_TYPE", "SERVICE_STATUS", "DISCHARGE_TYPE", "DISCHARGE_DATE", "DISCHARGE_YEAR", "SPECIALTY", "MILITARY_NO") AS
  SELECT
    PA.EMP_ID                   AS EMP_ID,
    FC7.CD_NM                   AS MILITARY_TYPE,
    FC1.CD_NM                   AS MILITARY_BRANCH,
    FC2.CD_NM                   AS MILITARY_RANK,
    FC6.CD_NM                   AS SERVICE_TYPE,
    FC5.CD_NM                   AS SERVICE_STATUS,
    FC3.CD_NM                   AS DISCHARGE_TYPE,
    PA.OUT_YMD                  AS DISCHARGE_DATE,
    CASE
        WHEN PA.OUT_YMD IS NOT NULL THEN
            SUBSTR(PA.OUT_YMD, 1, 4)
        ELSE NULL
    END                         AS DISCHARGE_YEAR,
    FC4.CD_NM                   AS SPECIALTY,
    PA.ARMY_NO                  AS MILITARY_NO
FROM PHM_ARMY PA
LEFT JOIN FRM_CODE FC1 ON FC1.CD = PA.ARMY_BRANCH_CD AND FC1.CD_KIND = 'PHM_ARMY_BRANCH_CD'
LEFT JOIN FRM_CODE FC2 ON FC2.CD = PA.ARMY_CLASS_CD AND FC2.CD_KIND = 'PHM_ARMY_CLASS_CD'
LEFT JOIN FRM_CODE FC3 ON FC3.CD = PA.ARMY_DISCHARGE_CD AND FC3.CD_KIND = 'PHM_ARMY_DISCHARGE_CD'
LEFT JOIN FRM_CODE FC4 ON FC4.CD = PA.ARMY_MTALENT_CD AND FC4.CD_KIND = 'PHM_ARMY_MTALENT_CD'
LEFT JOIN FRM_CODE FC5 ON FC5.CD = PA.ARMY_NO_REASON_CD AND FC5.CD_KIND = 'PHM_ARMY_NO_REASON_CD'
LEFT JOIN FRM_CODE FC6 ON FC6.CD = PA.ARMY_SERV_CD AND FC6.CD_KIND = 'PHMARMY_SERV_CD'
LEFT JOIN FRM_CODE FC7 ON FC7.CD = PA.ARMY_TYPE_CD AND FC7.CD_KIND = 'PHM_ARMY_TYPE_CD';

GRANT SELECT ON "H552_RND"."V_AI_MILITARY" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_MILITARY.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_MILITARY.MILITARY_TYPE IS '군 종류 (육군, 해군, 공군, 해병대 등)';
COMMENT ON COLUMN H552_RND.V_AI_MILITARY.MILITARY_BRANCH IS '병과 주특기';
COMMENT ON COLUMN H552_RND.V_AI_MILITARY.MILITARY_RANK IS '최종 계급 (병장, 상병 등)';
COMMENT ON COLUMN H552_RND.V_AI_MILITARY.SERVICE_STATUS IS '군필 여부 (군필, 미필, 면제 등)';
COMMENT ON COLUMN H552_RND.V_AI_MILITARY.DISCHARGE_TYPE IS '전역사유';
COMMENT ON COLUMN H552_RND.V_AI_MILITARY.DISCHARGE_DATE IS '전역일자';
COMMENT ON COLUMN H552_RND.V_AI_MILITARY.DISCHARGE_YEAR IS '전역한 연도 (YYYY)';
COMMENT ON COLUMN H552_RND.V_AI_MILITARY.MILITARY_NO IS '군번';


-- H552_RND.V_AI_REWARD source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_REWARD" ("EMP_ID", "REWARD_TYPE", "REWARD_KIND", "REWARD_REASON", "REWARD_CONTENT", "REWARD_DATE", "REWARD_YEAR", "AWARDING_ORG", "REWARD_AMOUNT", "REWARD_NO") AS
  SELECT
    PM.EMP_ID                   AS EMP_ID,
    FC3.CD_NM                   AS REWARD_TYPE,
    FC2.CD_NM                   AS REWARD_KIND,
    PM.PPM_DESC                 AS REWARD_REASON,
    PM.PRIZE_DESC               AS REWARD_CONTENT,
    PM.PPM_YMD                  AS REWARD_DATE,
    CASE
        WHEN PM.PPM_YMD IS NOT NULL THEN
            SUBSTR(PM.PPM_YMD, 1, 4)
        ELSE NULL
    END                         AS REWARD_YEAR,
    PM.PPM_ORG_NM               AS AWARDING_ORG,
    PM.PPM_MON                  AS REWARD_AMOUNT,
    PM.PPM_NO                   AS REWARD_NO
FROM PPM_MNT PM
LEFT JOIN FRM_CODE FC2 ON FC2.CD = PM.KIND_CD AND FC2.CD_KIND = 'PPM_KIND_CD'
LEFT JOIN FRM_CODE FC3 ON FC3.CD = PM.TYPE_CD AND FC3.CD_KIND = 'PPM_TYPE_CD';

GRANT SELECT ON "H552_RND"."V_AI_REWARD" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_REWARD.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_REWARD.REWARD_TYPE IS '상벌 구분 (포상, 징계)';
COMMENT ON COLUMN H552_RND.V_AI_REWARD.REWARD_KIND IS '상벌 종류';
COMMENT ON COLUMN H552_RND.V_AI_REWARD.REWARD_REASON IS '사유';
COMMENT ON COLUMN H552_RND.V_AI_REWARD.REWARD_DATE IS '일자';
COMMENT ON COLUMN H552_RND.V_AI_REWARD.REWARD_YEAR IS '상벌 발생 연도 (YYYY)';
COMMENT ON COLUMN H552_RND.V_AI_REWARD.AWARDING_ORG IS '기관';
COMMENT ON COLUMN H552_RND.V_AI_REWARD.REWARD_AMOUNT IS '포상금 금액';

-- H552_RND.V_AI_SCHOLAR source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_SCHOLAR" ("EMP_ID", "EMP_NAME", "POSITION", "MAJOR_CODE", "MAJOR_NAME", "DOUBLE_MAJOR_NAME", "SCHOOL_NAME", "ADMISSION_DATE", "GRADUATION_DATE", "SUB_MAJOR_CD", "SUB_MAJOR_NM", "SCHOOL_LOCATION_CODE", "SCHOOL_LOCATION_NAME") AS
  SELECT
    PS.EMP_ID AS EMP_ID,
    PN.LAST_NM AS EMP_NAME,
    FC.CD_NM AS POSITION,
    PS.MAJOR_CD AS MAJOR_CODE,
    PS.MAJOR_NM AS MAJOR_NAME,
    PS.DOU_MAJOR_NM AS DOUBLE_MAJOR_NAME,
    FC2.CD_NM AS SCHOOL_NAME,
    PS.STA_YM AS ADMISSION_DATE,
    PS.END_YM AS GRADUATION_DATE,
    PS.SUB_MAJOR_CD AS SUB_MAJOR_CD,
    PS.SUB_MAJOR_NM AS SUB_MAJOR_NM,
    PS.SCH_PLACE_CD AS SCHOOL_LOCATION_CODE,
    PS.SCH_PLACE_NM AS SCHOOL_LOCATION_NAME
FROM PHM_SCHOLAR PS
JOIN PHM_EMP PE
  ON PE.EMP_ID = PS.EMP_ID
JOIN PHM_NAME PN
  ON PN.EMP_ID = PS.EMP_ID
LEFT JOIN FRM_CODE FC2
  ON FC2.CD = PS.SCH_CD
 AND FC2.CD_KIND = 'PHM_SCH_CD'
LEFT JOIN FRM_CODE FC
  ON FC.CD = PE.POS_CD
 AND FC.CD_KIND = 'PHM_POS_CD';

GRANT SELECT ON "H552_RND"."V_AI_SCHOLAR" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.EMP_ID IS '평가자 ID';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.EMP_NAME IS '사원 이름';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR."POSITION" IS '직위';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.MAJOR_NAME IS '전공학과 명';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.DOUBLE_MAJOR_NAME IS '복수 전공 명';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.SCHOOL_NAME IS '학교 명';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.ADMISSION_DATE IS '입학일자';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.GRADUATION_DATE IS '졸업일자';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.SUB_MAJOR_NM IS '부전공 명';
COMMENT ON COLUMN H552_RND.V_AI_SCHOLAR.SCHOOL_LOCATION_NAME IS '학교 위치(소재지)';


-- H552_RND.V_AI_TRAINING source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_TRAINING" ("EMP_ID", "TRAINING_YEAR", "COURSE_TYPE", "COURSE_GRADE", "COURSE_FIELD", "COURSE_NAME", "INSTITUTION_TYPE", "INSTITUTION_NAME", "TRAINING_LOCATION", "TRAINING_TYPE", "START_DATE", "END_DATE", "TRAINING_COST", "COMPLETION_POINTS", "COMPLETION_HOURS", "COMPLETION_STATUS", "REFUND_AMOUNT") AS
  SELECT
    PED.EMP_ID                  AS EMP_ID,
    PED.EDU_YY                  AS TRAINING_YEAR,
    FC1.CD_NM                   AS COURSE_TYPE,
    FC2.CD_NM                   AS COURSE_GRADE,
    FC3.CD_NM                   AS COURSE_FIELD,
    PED.EDU_NM                  AS COURSE_NAME,
    FC4.CD_NM                   AS INSTITUTION_TYPE,
    PED.EDU_ORG_NM              AS INSTITUTION_NAME,
    FC5.CD_NM                   AS TRAINING_LOCATION,
    FC6.CD_NM                   AS TRAINING_TYPE,
    PED.STA_YMD                 AS START_DATE,
    PED.END_YMD                 AS END_DATE,
    PED.REAL_AMT                AS TRAINING_COST,
    PED.RESULT_PNT              AS COMPLETION_POINTS,
    PED.RESULT_TIMES            AS COMPLETION_HOURS,
    CASE PED.RESULT_YN
        WHEN 'Y' THEN '수료'
        WHEN 'N' THEN '미수료'
        ELSE PED.RESULT_YN
    END                         AS COMPLETION_STATUS,
    PED.RETURN_AMT              AS REFUND_AMOUNT
FROM PHM_EDU PED
LEFT JOIN FRM_CODE FC1 ON FC1.CD = PED.EDU_CD AND FC1.CD_KIND = 'PHM_EDU_CD'
LEFT JOIN FRM_CODE FC2 ON FC2.CD = PED.EDU_GRD_CD AND FC2.CD_KIND = 'PHM_EDU_GRD_CD'
LEFT JOIN FRM_CODE FC3 ON FC3.CD = PED.EDU_KIND_CD AND FC3.CD_KIND = 'PHM_EDU_KIND_CD'
LEFT JOIN FRM_CODE FC4 ON FC4.CD = PED.EDU_ORG_CD AND FC4.CD_KIND = 'PHM_EDU_ORG_CD'
LEFT JOIN FRM_CODE FC5 ON FC5.CD = PED.EDU_PLA_CD AND FC5.CD_KIND = 'PHM_EDU_PLA_CD'
LEFT JOIN FRM_CODE FC6 ON FC6.CD = PED.EDU_TYPE_CD AND FC6.CD_KIND = 'PHM_EDU_TYPE_CD';

GRANT SELECT ON "H552_RND"."V_AI_TRAINING" TO "MUSER";

COMMENT ON COLUMN H552_RND.V_AI_TRAINING.EMP_ID IS '사원 고유 식별 번호 (FK → V_AI_EMPLOYEE)';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.TRAINING_YEAR IS '교육 실시 연도';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.COURSE_GRADE IS '등급';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.COURSE_NAME IS '교육 과정 이름';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.TRAINING_LOCATION IS '교육장소';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.START_DATE IS '교육시작일자';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.END_DATE IS '교육종료일자';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.TRAINING_COST IS '교육비용';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.COMPLETION_POINTS IS '총이수포인트';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.COMPLETION_HOURS IS '총 이수 시간';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.COMPLETION_STATUS IS '수료 여부 (수료, 미수료)';
COMMENT ON COLUMN H552_RND.V_AI_TRAINING.REFUND_AMOUNT IS '환급금액';


-- H552_RND.V_AI_FEEDBACK source

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "H552_RND"."V_AI_FEEDBACK" ("RATEE_ID", "COMPANY_CD", "LOCALE_CD", "PEE_DEFINITION_ID", "APPR_ID", "APPR_NM", "PEE_TYPE_CD", "PEE_TYPE_NM", "EMP_ORG_ID", "EMP_ORG_NM", "RATEE_ORG_ID", "RATEE_ORG_NM", "RATEE_GROUP_ID", "RATEE_GROUP_NM", "RATEE_LEVEL_CD", "RATEE_LEVEL_NM", "EMP_ID", "EMP_NO", "EMP_NM", "APPR_SCORE", "APPR_GRADE", "RK", "PEE_OPINION", "APPR_SCORE_OPEN_YN", "APPR_GRADE_OPEN_YN", "APPR_RANK_OPEN_YN", "APPR_OPINION_OPEN_YN", "END_YMD", "APPR_YMD") AS 
  SELECT  RATEE_ID                  as Evaluator_employee_ID,
          COMPANY_CD                as Company_code,
          LOCALE_CD                 as Locale_code,
          PEE_DEFINITION_ID         as DEFINITION_ID,
          APPR_ID                   as Evaluation_ID,
          APPR_NM                   as Evaluation_name,
          PEE_TYPE_CD               as Evaluation_type_code,
          PEE_TYPE_NM               as Evaluation_type_name,
          EMP_ORG_ID                as Employee_organization_code,
          EMP_ORG_NM                as Employee_organization_name,
          RATEE_ORG_ID              as Employee_org_identifier_R,
          RATEE_ORG_NM              as Employee_org_name_R,
          RATEE_GROUP_ID            as Employee_group_identifier,
          RATEE_GROUP_NM            as Employee_group_name,
          RATEE_LEVEL_CD            as Position_job_level_code,
          RATEE_LEVEL_NM            as Position_job_level_name,
          EMP_ID                    as Employee_unique_identifier,
          EMP_NO                    as Employee_number,
          EMP_NM                    as Employee_name,
          APPR_SCORE                as Evaluation_score,
          APPR_GRADE                as Evaluation_grade,
          RK                        as Ranking,
          PEE_OPINION               as Evaluator_comments,
          APPR_SCORE_OPEN_YN        as Whether_evaluation_score_is_disclosed,
          APPR_GRADE_OPEN_YN        as Whether_evaluation_grade_is_disclosed,
          APPR_RANK_OPEN_YN         as Whether_ranking_are_disclosed,
          APPR_OPINION_OPEN_YN      as Whether_opinion_are_disclosed_,
          END_YMD                   as Evaluation_end_date,
          APPR_YMD                  as Evaluation_date
   FROM (SELECT C.RATEE_ID,
                  E.COMPANY_CD,
                  E.LOCALE_CD,
                  A.PEE_DEFINITION_ID,
                  B.APPR_ID,
                  B.APPR_NM,
                  B.PEE_TYPE_CD,
                  F_FRM_CODE_NM (E.COMPANY_CD,
                                 E.LOCALE_CD,
                                 'PEE_TYPE_CD',
                                 B.PEE_TYPE_CD,
                                 C.END_YMD,
                                 '1')
                     AS PEE_TYPE_NM,
                  C.EMP_ORG_ID,
                  F_FRM_ORM_ORG_NM (C.EMP_ORG_ID,
                                    E.LOCALE_CD,
                                    B.END_YMD,
                                    '11')
                     AS EMP_ORG_NM,
                  C.RATEE_ORG_ID,
                  F_FRM_ORM_ORG_NM (C.RATEE_ORG_ID,
                                    E.LOCALE_CD,
                                    B.APPR_YMD,
                                    '11')
                     AS RATEE_ORG_NM,
                  C.RATEE_GROUP_ID,
                  F_PEE_GET_RATEE_GROUP_INFO (E.COMPANY_CD,
                                              C.RATEE_GROUP_ID,
                                              'RATEE_GROUP_NM')
                     AS RATEE_GROUP_NM,
                  C.RATEE_LEVEL_CD,
                  F_FRM_CODE_NM (E.COMPANY_CD,
                                 E.LOCALE_CD,
                                 'PEE_RATEE_LEVEL_CD',
                                 C.RATEE_LEVEL_CD,
                                 C.END_YMD,
                                 '1')
                     AS RATEE_LEVEL_NM,
                  E.EMP_ID,
                  E.EMP_NO,
                  E.EMP_NM,
                  CASE
                     WHEN D.FIXED_SCORE > 0 THEN D.FIXED_SCORE
                     ELSE NULL
                  END
                     AS APPR_SCORE,
                  F_FRM_CODE_NM (E.COMPANY_CD,
                                 E.LOCALE_CD,
                                 'PEE_APPR_GRADE_CD',
                                 D.FIXED_GRADE,
                                 C.END_YMD,
                                 '1')
                     AS APPR_GRADE,
                  F_PEE_GET_APPR_GRADE_RANK (C.RATEE_ID, 'RANK') AS RK,
                  F_PEE_GET_APPR_OPINION (E.COMPANY_CD,
                                          E.LOCALE_CD,
                                          C.RATEE_ID,
                                          NULL)
                     AS PEE_OPINION,
                  XF_NVL_C (B.APPR_SCORE_OPEN_YN, 'N') AS APPR_SCORE_OPEN_YN,
                  XF_NVL_C (B.APPR_GRADE_OPEN_YN, 'N') AS APPR_GRADE_OPEN_YN,
                  XF_NVL_C (B.APPR_RANK_OPEN_YN, 'N') AS APPR_RANK_OPEN_YN,
                  XF_NVL_C (B.APPR_OPINION_OPEN_YN, 'N')
                     AS APPR_OPINION_OPEN_YN,
                  XF_NVL_C (C.EXCEPT_YN, 'N') AS EXCEPT_YN,
                  XF_NVL_C (B.CLOSE_YN, 'N') AS CLOSE_YN,
                  XF_NVL_C (B.FEEDBACK_YN, 'N') AS FEEDBACK_YN,
                  C.END_YMD AS END_YMD,
                  B.APPR_YMD
             FROM PEE_DEFINITION A,
                  PEE_APPR_AGGREGATE B,
                  PEE_RATEE C,
                  PEE_APPR_RESULT D,
                  VI_FRM_PHM_EMP E
            WHERE     A.PEE_DEFINITION_ID = B.PEE_DEFINITION_ID
                  AND B.APPR_ID = C.APPR_ID
                  AND C.RATEE_ID = D.RATEE_ID
                  AND C.RATEE_EMP_ID = E.EMP_ID
                  AND A.COMPANY_CD = E.COMPANY_CD);

GRANT SELECT ON "H552_RND"."V_AI_FEEDBACK" TO "MUSER";

COMMENT ON TABLE H552_RND.V_AI_FEEDBACK IS '평가, 직원 평가  (EMP_ID로 V_AI_EMPLOYEE와 JOIN, 1:N)';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.RATEE_ID IS '평가자 ID';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.PEE_DEFINITION_ID IS '회사코드';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.APPR_ID IS '평가번호';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.APPR_NM IS '평가 명';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.PEE_TYPE_CD IS '평가 종류 코드';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.PEE_TYPE_NM IS '평가 이름';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.EMP_ORG_ID IS '소속 부서 코드';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.EMP_ORG_NM IS '소속 부서 명';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.RATEE_GROUP_ID IS '소속 그룹 코드';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.RATEE_GROUP_NM IS '소속 그룹 명';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.RATEE_LEVEL_CD IS '직책 코드';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.RATEE_LEVEL_NM IS '직책 명';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.EMP_ID IS '사원번호';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.EMP_NO IS '직원번호';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.EMP_NM IS '이름';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.APPR_SCORE IS '평가 점수';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.APPR_GRADE IS '평가등급';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.RK IS '주석';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.PEE_OPINION IS '평가자 의견';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.APPR_SCORE_OPEN_YN IS '평가 점수 공개 여부';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.APPR_GRADE_OPEN_YN IS '평가등급 공개 여부';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.APPR_RANK_OPEN_YN IS '랭킹 공개 여부';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.END_YMD IS '평가종료일자';
COMMENT ON COLUMN H552_RND.V_AI_FEEDBACK.APPR_YMD IS '평가 일자';